install numpy by running from command prompt "conda install numpy" or "pip install numpy"

## Arrays

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [9]:
arr = np.array(my_list)
# turns list into array (1 dimension)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_mat)
# turns list of lists into array (2D)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

MORE COMMON WAY OF CREATING ARRAYS

In [76]:
np.arange(0,10) #creates array using a range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,11,2) #can also include a step size parameter

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.zeros(3) #creates 1D array of zeroes

array([ 0.,  0.,  0.])

In [19]:
np.zeros((5,5)) #creates 2D array of zeroes 
# (note the argument is a tuple; not simply 2 numbers)

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [20]:
np.zeros((2,3)) #2 rows, 3 columns

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [25]:
np.linspace(0,5,10) #returns 1D array; 10 items evenly spaced from 0 to 5
# with arange you specify the interval
# but with linspace you specify the number of items

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [27]:
np.eye(4) #creates IDENTITY MATRIX ; with n rows/cols

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [32]:
np.random.rand(5,4) #creates array of given shape, populates with 
# random numbers, uniformly distributed from 0 to 1

array([[ 0.14002576,  0.67242519,  0.35051238,  0.00665614],
       [ 0.09151692,  0.47456104,  0.27450189,  0.55571565],
       [ 0.95925719,  0.78316459,  0.50858686,  0.34361285],
       [ 0.40994695,  0.68493203,  0.30917204,  0.57047047],
       [ 0.95744054,  0.14200557,  0.9875294 ,  0.22516995]])

In [35]:
np.random.randn(4,4) #creates array, populated with
# random numbers, from "standard normal" distribution

array([[-0.96198432, -1.88250192, -0.44539079, -0.87025966],
       [ 0.15056286, -0.30710896, -0.90532721, -0.54140097],
       [-0.90452996,  0.20231835,  0.47859577, -0.81614192],
       [-0.77955533,  0.32122351,  0.99670752,  0.50999627]])

In [41]:
np.random.randint(1,100,(5,5)) #low, high, size; random integers 
#between low and high inputs

array([[17, 45, 81, 68, 89],
       [45,  2, 23, 30, 85],
       [55,  7, 81, 10, 89],
       [88,  7,  9, 33, 64],
       [71, 66, 91, 72, 90]])

In [42]:
np.random.randint(1,100)

58

## BASIC APPLICATIONS

In [43]:
arr = np.arange(25)

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [46]:
ranarr = np.random.randint(0,50,10)
ranarr

array([ 0,  0, 31,  9, 43, 36, 31,  0, 42,  8])

In [66]:
arr.reshape(5,5) #"reshapes" a m x n array to a u x v array 
# (u and v given by inputs); total size/number of elements must be constant

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [69]:
arr.shape #reports back the shape of the array

(25,)

In [70]:
arr.reshape(5,5).shape

(5, 5)

In [65]:
ranarr.reshape(10,1)

array([[ 0],
       [ 0],
       [31],
       [ 9],
       [43],
       [36],
       [31],
       [ 0],
       [42],
       [ 8]])

In [56]:
print(ranarr.max()) #finds max value in array
print(ranarr.min()) #finds min

43
0


In [58]:
print(ranarr.argmax()) #finds INDEX LOCATION of max value

4


In [62]:
ranarr[4] #gets the element at index location 4

43

In [72]:
arr.dtype #reports back the data type in the array


dtype('int32')

## INDEXING AND SELECTION

In [98]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arr[8] #returns value at index 8; just like with python lists

8

In [81]:
arr[1:5] #returns values from index 1 to index 5

array([1, 2, 3, 4])

In [82]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [83]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [99]:
# IMPORTANT NOTE: slices of arrays (i.e., using the brackets with range)
# is just creating a "view" of the original array.
# So changes to "slices" are actually changes to the ORIGINAL array
slice_of_arr = arr[8:11]
print(slice_of_arr)
slice_of_arr[:] = 99
print(slice_of_arr)
print(arr)

[ 8  9 10]
[99 99 99]
[ 0  1  2  3  4  5  6  7 99 99 99]


In [103]:
#if you actually want to create a separate copy,
#then you MUST use .copy()
arr_copy = arr.copy()
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7, 99, 99, 99])

In [104]:
slice_of_arr = arr_copy[8:11]
print(slice_of_arr)
slice_of_arr[:] = 1111
print(slice_of_arr)
print(arr)
print(arr_copy)

[99 99 99]
[1111 1111 1111]
[ 0  1  2  3  4  5  6  7 99 99 99]
[   0    1    2    3    4    5    6    7 1111 1111 1111]


In [107]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [109]:
arr_2d[0] #grabs row 0

array([ 5, 10, 15])

In [113]:
arr_2d[0][2] #grabs element at row 0 , col 2

15

In [114]:
arr_2d[0,2] # a better way to grab element at row 0, col 2

15

In [116]:
arr_2d[:,2] #grabs all rows, col 2

array([15, 30, 45])

In [129]:
arr_2d[1:,:2] #grabs from rows 1 and beyond, cols before 2

array([[20, 25],
       [35, 40]])

In [131]:
arr_A = np.arange(1,11)
arr_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [133]:
bool_arr = arr_A>5
bool_arr #now you have a boolean array

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True], dtype=bool)

In [135]:
arr_A[bool_arr] #can use the BOOLEAN ARRAY to only pull where index is TRUE
# like a filter

array([ 6,  7, 99, 99, 99])

In [140]:
#combining into one step
arr_A[arr_A>5]

array([ 6,  7,  8,  9, 10])

## OPERATIONS
- Array with Array
- Array with Scalars
- Universal Array Functions

In [142]:
arr_O = np.arange(0,11)
arr_O

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [143]:
arr_O + arr_O

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [144]:
arr_O * arr_O

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [145]:
arr_O *2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [146]:
arr_O / 2

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])

In [147]:
arr_O - 1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [148]:
arr_O **2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [149]:
np.sqrt(arr_O)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [150]:
np.exp(arr_O)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [151]:
np.max(arr_O)

10

In [152]:
arr_O.max()

10

https://docs.scipy.org/doc/numpy/reference/routines.math.html